spring.application.name=backend

spring.config.import=optional:file:.env[.properties]

spring.session.jdbc.initialize-schema=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}?prepareThreshold=0
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#server configuration
server.port=8080

#JWT configuration
jwt.secret=your_jwt_secret_key
jwt.expiration=3600000
jwt.prefix=Bearer
jwt.header=Authorization

#swagger configuration
swagger.api.title=Your API Title
swagger.api.description=Your API Description
swagger.api.version=1.0.0
swagger.api.terms-of-service-url=http://example.com/terms
swagger.api.contact.name=Your Name
swagger.api.contact.url=http://example.com/contact  
swagger.api.contact.email=your.email@example.com

# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG

# CORS configuration
cors.allowed-origins=*
cors.allowed-methods=GET,POST,PUT,DELETE
cors.allowed-headers=Content-Type,Authorization
spring.graphql.cors.exposed-headers=Authorization
cors.allow-credentials=true
cors.max-age=3600

#security configuration
spring.security.user.name=admin
spring.security.user.password=adminpassword
#spring.security.user.roles=USER,ADMIN
